# Generated by Django 4.0.5 on 2022-06-06 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='production_year',
        ),
    ]
