# Generated by Django 4.0.5 on 2022-06-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_production_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='img.png', upload_to='movies/'),
        ),
    ]
